name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/streamlit-app -f deployment/web-deployment/Dockerfile .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/streamlit-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCP_RUN_SERVICE }} \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/streamlit-app \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated

